PROJ = violet_example
TOPMODULE = top_violet_example

TOP_SRC = top/top_violet_example.v

VIOLET_SRC = ../violet/rx.v ../violet/tx.v ../violet/command_rx.v ../violet/violet.v

VERILOG_SRC = $(TOP_SRC) $(VIOLET_SRC) 

include support/colorveri.mk
